Model: 
    name : "NN"
    input_size: 10
    hidden_size: 16
    hidden_layer: 3
    output_size: 1
    epochs: 100
    batch_size: 16
    criterion: 'MSE'
    optim: 
        name: Adam
        lr: 0.001
    save: True
    save_path: 'trained_models/NN_noise_soil.pkl'
    gpu : True

Seed: [0,1,2,3,4]

Data:
    data_path : ['../results/lut_based_inversion/soil/prosail_danner-etal_switzerland_soil_lai-cab-ccc-car_lut_no-constraints.pkl']
    test_data_path : ['../results/lut_based_inversion/test/prosail_danner-etal_switzerland_soil_lai-cab-ccc-car_lut_no-constraints.pkl']
    baresoil_samples : ['../results/GEE_baresoil_v2/sampled_pixels_31TGM.pkl', '../results/GEE_baresoil_v2/sampled_pixels_31TGN.pkl', '../results/GEE_baresoil_v2/sampled_pixels_32TLT.pkl', '../results/GEE_baresoil_v2/sampled_pixels_32TMT.pkl', '../results/GEE_baresoil_v2/sampled_pixels_32TNT.pkl']
    val_data_path : '../results/validation_data_extended_angles_shift.pkl'
    train_cols : ['B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B11', 'B12']
    target_col : 'lai'   
    test_size : 0.2 
    normalize: True

Grid:
    lr: [0.01, 0.001, 0.0001]
    hidden_size : [8, 16, 32]
    hidden_layer: [1, 2, 3]
    batch_size: [4, 8, 16]
    optim: ['Adam', 'SGD']
    criterion: ['MSE', 'L1']


