Model: 
    name : "NN"
    input_size: 12  
    hidden_size: 10
    output_size: 1
    epochs: 100
    batch_size: 64
    optim: 
        name: Adam
        lr: 0.01
    save: True
    save_path: 'NN_nosoil_test.pkl'

Seed: 42

Data:
    data_path : ['../results/lut_based_inversion/prosail_danner-etal_switzerland_S2A_lai-cab-ccc-car_lut_no-constraints.pkl', '../results/lut_based_inversion/prosail_danner-etal_switzerland_S2B_lai-cab-ccc-car_lut_no-constraints.pkl']
    train_cols : ['B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B09', 'B10', 'B11', 'B12']
    target_col : 'lai'   
    test_size : 0.2 
    normalize: True


