Model: 
    name : "SVR"
    C: 3
    epsilon: 0.1
    k_folds: 4
    save: False

Seed: 42

Data:
    data_path : '../results/lut_based_inversion/prosail_danner-etal_switzerland_S2A_lai-cab-ccc-car_lut_no-constraints.pkl'
    train_cols : ['B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B09', 'B10', 'B11', 'B12']
    target_col : 'lai'   
    test_size : 0.2 
    normalize: True


