Model: 
    name : "RF"
    n_estimators: 100
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
    k_folds : 4
    save: True
    save_path: 'RF_soil_test.pkl'

Seed: 42

Data:
    data_path : ['../results/lut_based_inversion/prosail_danner-etal_switzerland_S2A_lai-cab-ccc-car_lut_no-constraints_soil.pkl', '../results/lut_based_inversion/prosail_danner-etal_switzerland_S2B_lai-cab-ccc-car_lut_no-constraints_soil.pkl']
    test_data_path : '../results/validation_data.pkl'
    train_cols : ['B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B11', 'B12']
    target_col : 'lai'   
    test_size : 0.2 
    normalize: True


