Model: 
    name : "RF"
    n_estimators: 100
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
    k_folds : 4
    save: True
    save_path: 'trained_models/RF_soilscaled22_inverse1_tuned.pkl'

Seed: 42

Data:
    data_path : ['../results/lut_based_inversion/soil_scaled/prosail_danner-etal_switzerland_lai-cab-ccc-car_lut_no-constraints_inverse1.pkl']
    baresoil_samples : ['../results/GEE_baresoil_v2/sampled_pixels_31TGM.pkl', '../results/GEE_baresoil_v2/sampled_pixels_31TGN.pkl', '../results/GEE_baresoil_v2/sampled_pixels_32TLT.pkl', '../results/GEE_baresoil_v2/sampled_pixels_32TMT.pkl', '../results/GEE_baresoil_v2/sampled_pixels_32TNT.pkl']
    test_data_path : '../results/validation_data_extended_lai.pkl'
    train_cols : ['B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B11', 'B12']
    target_col : 'lai'   
    test_size : 0.2 
    normalize: True

Grid:
    n_estimators: [100, 200, 500]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    max_features: [1, 'sqrt']


