Model: 
    name : "SVR"
    kernel : "linear"
    gamma : "scale"
    C: 1
    epsilon: 0.4
    k_folds: 4
    save: True
    save_path: 'trained_models/SVR_soil_inverse1_tuned.pkl'

Seed: 42

Data:
    data_path : ['../results/lut_based_inversion/soil_scaled/prosail_danner-etal_switzerland_lai-cab-ccc-car_lut_no-constraints_inverse1.pkl']
    baresoil_samples : ['../results/GEE_baresoil_v2/sampled_pixels_31TGM.pkl', '../results/GEE_baresoil_v2/sampled_pixels_31TGN.pkl', '../results/GEE_baresoil_v2/sampled_pixels_32TLT.pkl', '../results/GEE_baresoil_v2/sampled_pixels_32TMT.pkl', '../results/GEE_baresoil_v2/sampled_pixels_32TNT.pkl']
    test_data_path : '../results/validation_data_extended_lai.pkl'
    train_cols : ['B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B11', 'B12']
    target_col : 'lai'   
    test_size : 0.2 
    normalize: True


Grid:
    kernel : ['linear', 'poly', 'rbf', 'sigmoid']
    C: [0.1, 1, 10, 100]
    gamma: ['scale', 'auto']
    epsilon: [0.1, 0.2, 0.3, 0.4, 0.5]

