Model: 
    name : "NN"
    input_size: 10
    hidden_size: 10
    output_size: 1
    epochs: 100
    batch_size: 2
    optim: 
        name: Adam
        lr: 0.01
    save: True
    save_path: 'NN_soil2_test.pkl'
    gpu : False

Seed: 42

Data:
    data_path : ['../results/lut_based_inversion/prosail_danner-etal_switzerland_S2A_lai-cab-ccc-car_lut_no-constraints_soil2.pkl', '../results/lut_based_inversion/prosail_danner-etal_switzerland_S2B_lai-cab-ccc-car_lut_no-constraints_soil2.pkl']
    test_data_path : '../results/validation_data.pkl'
    train_cols : ['B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B11', 'B12']
    target_col : 'lai'   
    test_size : 0.2 
    normalize: True


